<a href="https://colab.research.google.com/github/it-ces/PUBLIC-AI/blob/main/Analytics/Z_standard(BIT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
## Iván Andrés Trujillo Abella
## ivantrujillo1229@gmail.com

In [102]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [103]:
df = pd.DataFrame({'var1': [ 10, 20, 40, 33, 21],
      'var2': [1, 0, 1 ,0 ,1 ],
      'var3': ['A', 'B', 'C', 'D', 'E']})
df_ = df.copy()
df2 = df.copy()

In [104]:
df

   var1  var2 var3
0    10     1    A
1    20     0    B
2    40     1    C
3    33     0    D
4    21     1    E

In [105]:
df.dtypes

var1     int64
var2     int64
var3    object
dtype: object

In [106]:
for var in df.columns:
  if df[var].dtypes.name == 'float64' or df[var].dtypes.name == 'int64':
    print(var)
    df[var] = (df[var] - df[var].mean())/ df[var].std(ddof = 0)

var1
var2

In [107]:
df # Var not requiere standardization

       var1      var2 var3
0 -1.405007  0.816497    A
1 -0.455678 -1.224745    B
2  1.442980  0.816497    C
3  0.778450 -1.224745    D
4 -0.360745  0.816497    E

In [108]:
stad = StandardScaler()
stad.fit_transform(df2[['var1']])

array([[-1.40500701],
       [-0.45567795],
       [ 1.44298017],
       [ 0.77844983],
       [-0.36074504]])

In [109]:
pd.DataFrame(stad.fit_transform(df2[['var1']]), columns = ['var1'])

       var1
0 -1.405007
1 -0.455678
2  1.442980
3  0.778450
4 -0.360745

HASTA AQUU!!

In [110]:
def is_binary(var, df):
  ideal = [0,1]  # not binary.......
  flag = True
  for num in df[var].unique():
    if num not in ideal:
      flag = False
  return flag

In [111]:
df_

   var1  var2 var3
0    10     1    A
1    20     0    B
2    40     1    C
3    33     0    D
4    21     1    E

In [112]:
is_binary("var2", df=df_)

True

In [113]:
is_binary("var2", df_)

True

In [114]:
for var in df_.columns:
  if df_[var].dtypes.name == 'float64' or df_[var].dtypes.name == 'int64':
    if is_binary(var, df_) == False:
      df_[var] = (df_[var] - df_[var].mean())/ df_[var].std()

In [115]:
is_binary("var2", df_)

True

In [116]:
df_

       var1  var2 var3
0 -1.256676     1    A
1 -0.407571     0    B
2  1.290641     1    C
3  0.696267     0    D
4 -0.322660     1    E

In [117]:
## Think in another problems that could arise for instance in liker test!!!!!