<a href="https://colab.research.google.com/github/it-ces/PUBLIC-AI/blob/main/Analytics/Z_standard(BIT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
## Iván Andrés Trujillo Abella
## ivantrujillo1229@gmail.com

In [67]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [68]:
df = pd.DataFrame({'var1': [ 10, 20, 40, 33, 21],
      'var2': [1, 0, 1 ,0 ,1 ],
      'var3': ['A', 'B', 'C', 'D', 'E']})
df_ = df.copy()
df2 = df.copy()

In [69]:
df

   var1  var2 var3
0    10     1    A
1    20     0    B
2    40     1    C
3    33     0    D
4    21     1    E

In [70]:
df.dtypes

var1     int64
var2     int64
var3    object
dtype: object

In [71]:
for var in df.columns:
  if df[var].dtypes.name == 'float64' or df[var].dtypes.name == 'int64':
    print(var)
    df[var] = (df[var] - df[var].mean())/ df[var].std(ddof = 0)

var1
var2

In [72]:
df # Var not requiere standardization

       var1      var2 var3
0 -1.405007  0.816497    A
1 -0.455678 -1.224745    B
2  1.442980  0.816497    C
3  0.778450 -1.224745    D
4 -0.360745  0.816497    E

In [73]:
stad = StandardScaler()
stad.fit_transform(df2[['var1', 'var2']])

array([[-1.40500701,  0.81649658],
       [-0.45567795, -1.22474487],
       [ 1.44298017,  0.81649658],
       [ 0.77844983, -1.22474487],
       [-0.36074504,  0.81649658]])

In [74]:
pd.DataFrame(stad.fit_transform(df2[['var1', 'var2']]), columns = ['var1', 'var2'])

       var1      var2
0 -1.405007  0.816497
1 -0.455678 -1.224745
2  1.442980  0.816497
3  0.778450 -1.224745
4 -0.360745  0.816497

HASTA AQUU!!

In [75]:
def is_binary(var, df):
  ideal = [0,1]  # not binary.......
  flag = True
  for num in df[var].unique():
    if num not in ideal:
      flag = False
  return flag

In [76]:
df_

   var1  var2 var3
0    10     1    A
1    20     0    B
2    40     1    C
3    33     0    D
4    21     1    E

In [77]:
is_binary("var2", df=df_)

True

In [78]:
is_binary("var2", df_)

True

In [79]:
for var in df_.columns:
  if df_[var].dtypes.name == 'float64' or df_[var].dtypes.name == 'int64':
    if is_binary(var, df_) == False:
      df_[var] = (df_[var] - df_[var].mean())/ df_[var].std()

In [80]:
is_binary("var2", df_)

True

In [81]:
df_

       var1  var2 var3
0 -1.256676     1    A
1 -0.407571     0    B
2  1.290641     1    C
3  0.696267     0    D
4 -0.322660     1    E

In [82]:
## Think in another problems that could arise for instance in liker test!!!!!