In [1]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [2]:
import numpy as np
def VIF(R):
  if R==1:
    return  np.inf
  else:
    return (1 / (1- R))

In [3]:
url = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/profit-firms.csv"

# Financial accounting

 * equity translate to patrimonio,
 * asset activo.
 * asset =  liabilities + equity

In [4]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

In [5]:
df = pd.read_csv(url)

In [6]:
df.head()

,asset,expense,liabilities,equity,investment,advertising,profit
0,950.407337,463.447881,297.887207,652.520130,28.071450,89.591507,2234.720616
1,943.151410,444.869429,299.336430,643.814980,37.771936,84.542885,2211.017903
2,996.472824,402.769708,299.645805,696.827019,3.474213,70.650397,2278.566400
3,986.593103,493.436828,300.093009,686.500094,66.294020,94.736669,2330.554933
4,940.636336,485.475549,300.995442,639.640894,13.881267,81.241172,2196.308255

In [7]:
df.corr()

,asset,expense,liabilities,equity,investment,advertising,profit
asset,1.000000,-0.037028,0.011083,0.999383,-0.048168,0.019226,0.774024
expense,-0.037028,1.000000,0.031262,-0.038118,0.105446,0.547100,0.311635
liabilities,0.011083,0.031262,1.000000,-0.024045,0.020196,-0.000463,0.009146
equity,0.999383,-0.038118,-0.024045,1.000000,-0.048867,0.019238,0.773526
investment,-0.048168,0.105446,0.020196,-0.048867,1.000000,-0.006335,-0.039475
advertising,0.019226,0.547100,-0.000463,0.019238,-0.006335,1.000000,0.637834
profit,0.774024,0.311635,0.009146,0.773526,-0.039475,0.637834,1.000000

In [8]:
# asset -> all goods that belong to the firm, cash, resources, properties , equipment, all "assests"
# equity -> asset - debt

In [9]:
df['sopecho'] = df['equity'] + df['liabilities']

In [10]:
df.head()

,asset,expense,liabilities,equity,investment,advertising,profit,sopecho
0,950.407337,463.447881,297.887207,652.520130,28.071450,89.591507,2234.720616,950.407337
1,943.151410,444.869429,299.336430,643.814980,37.771936,84.542885,2211.017903,943.151410
2,996.472824,402.769708,299.645805,696.827019,3.474213,70.650397,2278.566400,996.472824
3,986.593103,493.436828,300.093009,686.500094,66.294020,94.736669,2330.554933,986.593103
4,940.636336,485.475549,300.995442,639.640894,13.881267,81.241172,2196.308255,940.636336

In [11]:
import statsmodels.formula.api as smf

In [12]:
print(smf.ols("profit ~ equity + asset + liabilities", data= df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.599
Model:                            OLS   Adj. R-squared:                  0.597
Method:                 Least Squares   F-statistic:                     306.4
Date:                Sun, 12 Apr 2026   Prob (F-statistic):           4.16e-82
Time:                        05:05:02   Log-Likelihood:                -2170.3
No. Observations:                 413   AIC:                             4347.
Df Residuals:                     410   BIC:                             4359.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     311.5008    703.412      0.443      0.658   -1071.243    1694.245
equity          0.6622      0.778      0.851      0.395      -0.868       2.192
asset           1.3667      0.779      1.754      0.080      -0.165       2.898
liabilities     0.7045      1.555      0.453      0.651      -2.353       3.762
==============================================================================
Omnibus:                        0.213   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.899   Jarque-Bera (JB):                0.272
Skew:                           0.053   Prob(JB):                        0.873
Kurtosis:                       2.931   Cond. No.                     9.25e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.9e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [13]:
print(smf.ols("profit ~ asset + liabilities", data= df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.599
Model:                            OLS   Adj. R-squared:                  0.597
Method:                 Least Squares   F-statistic:                     306.4
Date:                Sun, 12 Apr 2026   Prob (F-statistic):           4.16e-82
Time:                        05:05:02   Log-Likelihood:                -2170.3
No. Observations:                 413   AIC:                             4347.
Df Residuals:                     410   BIC:                             4359.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     311.5008    703.412      0.443      0.658   -1071.243    1694.245
asset           2.0288      0.082     24.752      0.000       1.868       2.190
liabilities     0.0423      2.333      0.018      0.986      -4.544       4.629
==============================================================================
Omnibus:                        0.213   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.899   Jarque-Bera (JB):                0.272
Skew:                           0.053   Prob(JB):                        0.873
Kurtosis:                       2.931   Cond. No.                     3.08e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.08e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [14]:
print(smf.ols("profit ~ asset + equity ", data= df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.599
Model:                            OLS   Adj. R-squared:                  0.597
Method:                 Least Squares   F-statistic:                     306.4
Date:                Sun, 12 Apr 2026   Prob (F-statistic):           4.16e-82
Time:                        05:05:02   Log-Likelihood:                -2170.3
No. Observations:                 413   AIC:                             4347.
Df Residuals:                     410   BIC:                             4359.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    311.5008    703.412      0.443      0.658   -1071.243    1694.245
asset          2.0711      2.334      0.888      0.375      -2.516       6.658
equity        -0.0423      2.333     -0.018      0.986      -4.629       4.544
==============================================================================
Omnibus:                        0.213   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.899   Jarque-Bera (JB):                0.272
Skew:                           0.053   Prob(JB):                        0.873
Kurtosis:                       2.931   Cond. No.                     3.56e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.56e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [15]:
print(smf.ols("profit ~  equity  + liabilities", data= df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.599
Model:                            OLS   Adj. R-squared:                  0.597
Method:                 Least Squares   F-statistic:                     306.4
Date:                Sun, 12 Apr 2026   Prob (F-statistic):           4.16e-82
Time:                        05:05:02   Log-Likelihood:                -2170.3
No. Observations:                 413   AIC:                             4347.
Df Residuals:                     410   BIC:                             4359.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     311.5008    703.412      0.443      0.658   -1071.243    1694.245
equity          2.0288      0.082     24.752      0.000       1.868       2.190
liabilities     2.0711      2.334      0.888      0.375      -2.516       6.658
==============================================================================
Omnibus:                        0.213   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.899   Jarque-Bera (JB):                0.272
Skew:                           0.053   Prob(JB):                        0.873
Kurtosis:                       2.931   Cond. No.                     2.21e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.21e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [16]:
df.columns

Index(['asset', 'expense', 'liabilities', 'equity', 'investment',
       'advertising', 'profit', 'sopecho'],
      dtype='object')

In [17]:
print(smf.ols('profit ~ advertising ', data = df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.407
Model:                            OLS   Adj. R-squared:                  0.405
Method:                 Least Squares   F-statistic:                     281.9
Date:                Sun, 12 Apr 2026   Prob (F-statistic):           1.50e-48
Time:                        05:05:02   Log-Likelihood:                -2251.2
No. Observations:                 413   AIC:                             4506.
Df Residuals:                     411   BIC:                             4515.
Df Model:                           1
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept    1897.8928     21.747     87.273      0.000    1855.144    1940.641
advertising     3.9991      0.238     16.790      0.000       3.531       4.467
==============================================================================
Omnibus:                      110.846   Durbin-Watson:                   1.798
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               19.871
Skew:                          -0.080   Prob(JB):                     4.84e-05
Kurtosis:                       1.937   Cond. No.                         714.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [18]:
print(smf.ols('profit ~ expense ', data = df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.097
Model:                            OLS   Adj. R-squared:                  0.095
Method:                 Least Squares   F-statistic:                     44.21
Date:                Sun, 12 Apr 2026   Prob (F-statistic):           9.42e-11
Time:                        05:05:03   Log-Likelihood:                -2338.0
No. Observations:                 413   AIC:                             4680.
Df Residuals:                     411   BIC:                             4688.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1927.6691     50.102     38.475      0.000    1829.181    2026.157
expense        0.7165      0.108      6.649      0.000       0.505       0.928
==============================================================================
Omnibus:                        7.587   Durbin-Watson:                   2.065
Prob(Omnibus):                  0.023   Jarque-Bera (JB):                4.672
Skew:                          -0.057   Prob(JB):                       0.0967
Kurtosis:                       2.492   Cond. No.                     6.79e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.79e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [19]:
print(smf.ols('profit ~ advertising + expense + equity', data = df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.987
Model:                            OLS   Adj. R-squared:                  0.986
Method:                 Least Squares   F-statistic:                 1.001e+04
Date:                Sun, 12 Apr 2026   Prob (F-statistic):               0.00
Time:                        05:05:03   Log-Likelihood:                -1469.2
No. Observations:                 413   AIC:                             2946.
Df Residuals:                     409   BIC:                             2963.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     601.0767     11.802     50.931      0.000     577.877     624.276
advertising     3.9086      0.043     90.916      0.000       3.824       3.993
expense        -0.0009      0.016     -0.059      0.953      -0.032       0.030
equity          1.9956      0.015    132.579      0.000       1.966       2.025
==============================================================================
Omnibus:                        1.840   Durbin-Watson:                   1.950
Prob(Omnibus):                  0.398   Jarque-Bera (JB):                1.656
Skew:                           0.042   Prob(JB):                        0.437
Kurtosis:                       2.701   Cond. No.                     2.27e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.27e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [20]:
X = df[[  'expense',  'equity', 'asset' ]]
vif_data = pd.DataFrame()
X = sm.add_constant(X)
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
vif_data

   feature           VIF
0    const  94490.706238
1  expense      1.002380
2   equity    811.417518
3    asset    811.350984

In [21]:
print(smf.ols(formula = 'profit ~ equity + expense + liabilities', data= df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.715
Model:                            OLS   Adj. R-squared:                  0.713
Method:                 Least Squares   F-statistic:                     342.3
Date:                Sun, 12 Apr 2026   Prob (F-statistic):          3.95e-111
Time:                        05:05:03   Log-Likelihood:                -2099.7
No. Observations:                 413   AIC:                             4207.
Df Residuals:                     409   BIC:                             4224.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     157.6858    593.750      0.266      0.791   -1009.497    1324.868
equity          2.0623      0.069     29.791      0.000       1.926       2.198
expense         0.7842      0.061     12.910      0.000       0.665       0.904
liabilities     1.2985      1.970      0.659      0.510      -2.575       5.172
==============================================================================
Omnibus:                        0.929   Durbin-Watson:                   2.055
Prob(Omnibus):                  0.628   Jarque-Bera (JB):                0.710
Skew:                           0.057   Prob(JB):                        0.701
Kurtosis:                       3.168   Cond. No.                     2.63e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.63e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [22]:
print(smf.ols(formula = 'profit ~ equity + expense ', data= df).fit().summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.715
Model:                            OLS   Adj. R-squared:                  0.713
Method:                 Least Squares   F-statistic:                     514.0
Date:                Sun, 12 Apr 2026   Prob (F-statistic):          1.92e-112
Time:                        05:05:03   Log-Likelihood:                -2100.0
No. Observations:                 413   AIC:                             4206.
Df Residuals:                     410   BIC:                             4218.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    547.3508     54.217     10.096      0.000     440.773     653.928
equity         2.0612      0.069     29.805      0.000       1.925       2.197
expense        0.7854      0.061     12.945      0.000       0.666       0.905
==============================================================================
Omnibus:                        0.792   Durbin-Watson:                   2.054
Prob(Omnibus):                  0.673   Jarque-Bera (JB):                0.580
Skew:                           0.048   Prob(JB):                        0.748
Kurtosis:                       3.156   Cond. No.                     2.25e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.25e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [23]:
model = smf.ols(formula = 'equity ~  asset + expense ', data=df).fit()

In [24]:
VIF(model.rsquared)

np.float64(811.4175175493477)

# Cuando la base es pequeña solucionamos a ojo
en el caso contrario camemos en un campo  ese campo selección de variables!!!
* backward o forward selection
* regularización
* genéticos ( ant - colony optimization)
* PCA me permite obtener una base de datos más pequeña y ortogonal...