In [ ]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/bankrupt-sector.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
for sector in df['sector'].unique():
  print(sector,df[df['sector']==sector]['bankrupt'].value_counts())

Technology bankrupt
0    24
1     1
Name: count, dtype: int64
Financial bankrupt
0    79
1    55
Name: count, dtype: int64
Health bankrupt
0    70
1    51
Name: count, dtype: int64
Construction bankrupt
0    33
1     5
Name: count, dtype: int64

In [ ]:
df['indicator']= 1

In [ ]:
df.groupby(by=['sector', 'bankrupt'])['indicator'].count()

sector        bankrupt
Construction  0           33
              1            5
Financial     0           79
              1           55
Health        0           70
              1           51
Technology    0           24
              1            1
Name: indicator, dtype: int64

In [ ]:
df.groupby('sector')['bankrupt'].value_counts(normalize=True)

sector        bankrupt
Construction  0           0.868421
              1           0.131579
Financial     0           0.589552
              1           0.410448
Health        0           0.578512
              1           0.421488
Technology    0           0.960000
              1           0.040000
Name: proportion, dtype: float64