In [47]:
import pandas as pd
import datetime

In [48]:
df = pd.read_csv('https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/intro_dates.csv')

In [49]:
df.head(2)

      Fecha_1              Fecha_2
0  01/10/2008  01/10/2020 10:00:00
1  04/10/2008  02/11/2021 11:00:03

In [50]:
df.info()
#observe that dates are strings (objects)!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Fecha_1  6 non-null      object
 1   Fecha_2  6 non-null      object
dtypes: object(2)
memory usage: 228.0+ bytes

In [51]:
# we can transform in the object oriented to handle this type
df['Fecha_1'] = pd.to_datetime(df['Fecha_1'], format="%d/%m/%Y")

In [52]:
df.info() # observe datetime64!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Fecha_1  6 non-null      datetime64[ns]
 1   Fecha_2  6 non-null      object
dtypes: datetime64[ns](1), object(1)
memory usage: 228.0+ bytes

#Formats strings...

%d	Day of month 01-31	31

%B	Month name, full version	December

%m	Month as a number 01-12	12

%y	Year, short version, without century	18

%Y	Year, full version	2018

%j	Day number of year 001-366	365

%H hour, %M minute, %S second.

In [54]:
df['Fecha_2'] = pd.to_datetime(df['Fecha_2'], format='%d/%m/%Y %H:%M:%S')

In [55]:
# get information!
df['día2'] = df['Fecha_2'].dt.day
df['mes2'] = df['Fecha_2'].dt.month
df['mes_name2'] = df['Fecha_2'].dt.month_name()
df['hora-fecha2'] =df['Fecha_2'].dt.hour

In [56]:
df

     Fecha_1             Fecha_2  día2  mes2 mes_name2  hora-fecha2
0 2008-10-01 2020-10-01 10:00:00     1    10   October           10
1 2008-10-04 2021-11-02 11:00:03     2    11  November           11
2 2008-10-15 2025-12-04 17:08:56     4    12  December           17
3 2008-11-24 2025-12-05 22:00:00     5    12  December           22
4 2009-05-04 2025-12-07 23:31:45     7    12  December           23
5 2009-06-06 2025-12-08 10:03:02     8    12  December           10

In [57]:
df['Fecha_1'].diff() # important operator

0        NaT
1     3 days
2    11 days
3    40 days
4   161 days
5    33 days
Name: Fecha_1, dtype: timedelta64[ns]

In [58]:
# we can rest two dates! and calculate the days of difference!

     Fecha_1             Fecha_2  día2  mes2 mes_name2  hora-fecha2
0 2008-10-01 2020-10-01 10:00:00     1    10   October           10
1 2008-10-04 2021-11-02 11:00:03     2    11  November           11
2 2008-10-15 2025-12-04 17:08:56     4    12  December           17
3 2008-11-24 2025-12-05 22:00:00     5    12  December           22
4 2009-05-04 2025-12-07 23:31:45     7    12  December           23
5 2009-06-06 2025-12-08 10:03:02     8    12  December           10

In [62]:
url2 ="https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/intro_dates2.csv"
df  = pd.read_csv(url2)

In [63]:
df.columns

Index(['start_date', 'end_date'], dtype='object')

In [66]:
df['start_date'] = pd.to_datetime(df['start_date'], format='%d-%m-%Y')
df['end_date'] = pd.to_datetime(df['end_date'], format='%Y-%m-%d')

In [74]:
(df['end_date'] - df['start_date']).dt.days

0    11354
1    14185
2    12772
3    10784
4     9883
5     7290
6    11324
dtype: int64