In [1]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

# Basic about financial statements...

## Return on Assets (ROA)

Return on Assets (ROA) is a financial ratio that shows how profitable a company is relative to its total assets. It measures how efficiently a company is using its assets to generate net income.

\begin{equation}
ROA  = \frac{Net Income}{Total Assets}
\end{equation}

High ROA → The company is efficiently using its assets to generate profit.

Low ROA → The company might not be using its assets effectively.

In [2]:
import pandas as pd

In [3]:
URL = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/restaurants_usd.csv"

In [4]:
df = pd.read_csv(URL)

In [5]:
df

    total_income   total_cost   total_assets
0   45174.762933   347.372216  175755.900622
1   70508.255431  1740.466248  178565.718836
2   61820.008760   960.264977  178082.990247
3   40058.577804  1615.546626  180418.611303
4   51341.348287 -1133.609844  179717.957127
5   78463.417343   -23.279032  178565.926134
6   28864.711905  1135.267854  173587.273745
7   53161.873433  2894.553980  177823.953156
8   73774.900444  1704.177640  176525.059445
9   47836.941054  1894.968558  172091.174433
10  50121.654913  2635.916444  179506.213639
11  57226.512540   941.041791  177857.396039
12  76516.900858  2198.516026  175798.621840
13  50607.948689  1021.225386  175045.697132
14  52978.597788    24.141087  172437.023933
15  53095.727729  1469.297520  176214.929929
16  85207.257763  2512.222554  176941.727350
17  84974.425406  2257.934109  173429.310853
18  70589.844704  1879.102168  178816.767700
19  63075.239990  4478.232720  172710.262037
20  67346.374572  2338.283417  169937.566622
21  76508.903045  2949.984871  178485.748894
22  46996.615114  4311.506312  174585.497194
23  72679.001896   492.880732  175335.055175
24  43128.478365   768.877611  173412.116965
25  50621.941186  3776.986189  171335.235782
26  69410.738868  1029.121367  179068.209121

In [6]:
df['net_income'] = df['total_income'] - df['total_cost']
df['ROA'] = df['net_income']/df['total_assets']
df.sort_values(by=['ROA'], ascending=False)[:5]

    total_income   total_cost   total_assets    net_income       ROA
17  84974.425406  2257.934109  173429.310853  82716.491297  0.476946
16  85207.257763  2512.222554  176941.727350  82695.035209  0.467357
5   78463.417343   -23.279032  178565.926134  78486.696375  0.439539
12  76516.900858  2198.516026  175798.621840  74318.384833  0.422747
21  76508.903045  2949.984871  178485.748894  73558.918174  0.412128

In [7]:
df.drop(columns=['net_income',  'total_assets' ], inplace = True)

In [8]:
df

    total_income   total_cost       ROA
0   45174.762933   347.372216  0.255055
1   70508.255431  1740.466248  0.385112
2   61820.008760   960.264977  0.341749
3   40058.577804  1615.546626  0.213077
4   51341.348287 -1133.609844  0.291985
5   78463.417343   -23.279032  0.439539
6   28864.711905  1135.267854  0.159744
7   53161.873433  2894.553980  0.282680
8   73774.900444  1704.177640  0.408275
9   47836.941054  1894.968558  0.266963
10  50121.654913  2635.916444  0.264535
11  57226.512540   941.041791  0.316464
12  76516.900858  2198.516026  0.422747
13  50607.948689  1021.225386  0.283279
14  52978.597788    24.141087  0.307094
15  53095.727729  1469.297520  0.292974
16  85207.257763  2512.222554  0.467357
17  84974.425406  2257.934109  0.476946
18  70589.844704  1879.102168  0.384252
19  63075.239990  4478.232720  0.339279
20  67346.374572  2338.283417  0.382541
21  76508.903045  2949.984871  0.412128
22  46996.615114  4311.506312  0.244494
23  72679.001896   492.880732  0.411704
24  43128.478365   768.877611  0.244271
25  50621.941186  3776.986189  0.273411
26  69410.738868  1029.121367  0.381875