In [ ]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
online = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/clothing-store-online.csv"
physical = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/clothing-store-physical.csv"
prices = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/clothing-store-prices.csv"

In [ ]:
online_df = pd.read_csv(online)
physical_df = pd.read_csv(physical)
prices_df = pd.read_csv(prices)

In [ ]:
# The total number of transaction could be in only one dataframe
online_df.head()

  id-product  id-client  quantities
0         A4          1           1
1         A4          2           1
2         A4          3           1
3         A4          4           1
4         A8          5           1

In [ ]:
physical_df.head()

  id-product  id-client  quantities
0         C7        701           1
1         C7        702           1
2         C7        703           2
3         C7        704           1
4         C7        705           1

In [ ]:
transactions = pd.concat([online_df, physical_df])

In [ ]:
transactions.head()

  id-product  id-client  quantities
0         A4          1           1
1         A4          2           1
2         A4          3           1
3         A4          4           1
4         A8          5           1

In [ ]:
prices_df.head()

  reference      price
0        A1  20.580006
1        A2  27.567961
2        A3  21.837506
3        A4  17.622064
4        A5  16.232090

In [ ]:
transactions.columns

Index(['id-product', 'id-client', 'quantities'], dtype='object')

In [ ]:
prices_df.columns

Index(['reference', 'price'], dtype='object')

In [ ]:
df = transactions.merge(prices_df,
                   left_on='id-product',
                   right_on='reference', indicator=True)

In [ ]:
df

    id-product  id-client  quantities reference      price _merge
0           A4          1           1        A4  17.622064   both
1           A4          2           1        A4  17.622064   both
2           A4          3           1        A4  17.622064   both
3           A4          4           1        A4  17.622064   both
4           A8          5           1        A8  21.102905   both
..         ...        ...         ...       ...        ...    ...
980         F4       1003           1        F4   9.617814   both
981         F4        878           1        F4   9.617814   both
982         F4        953           1        F4   9.617814   both
983         F3        935           1        F3  11.321542   both
984         F4        845           1        F4   9.617814   both

[985 rows x 6 columns]

In [ ]:
df['expense'] = df['price'] * df['quantities']

In [ ]:
df['total_expense'] = df.groupby(by=['id-client'])['expense'].transform("sum")

In [ ]:
df

,id-product,id-client,quantities,reference,price,_merge,expense,total_expense
0,A4,1,1,A4,17.622064,both,17.622064,17.622064
1,A4,2,1,A4,17.622064,both,17.622064,17.622064
2,A4,3,1,A4,17.622064,both,17.622064,17.622064
3,A4,4,1,A4,17.622064,both,17.622064,17.622064
4,A8,5,1,A8,21.102905,both,21.102905,21.102905
...,...,...,...,...,...,...,...,...
980,F4,1003,1,F4,9.617814,both,9.617814,20.939356
981,F4,878,1,F4,9.617814,both,9.617814,9.617814
982,F4,953,1,F4,9.617814,both,9.617814,9.617814
983,F3,935,1,F3,11.321542,both,11.321542,90.480104
984,F4,845,1,F4,9.617814,both,9.617814,9.617814

In [ ]:
df = df[-df.duplicated(['id-client'], keep='first')].reset_index(drop=True)

In [ ]:
df

,id-product,id-client,quantities,reference,price,_merge,expense,total_expense
0,A4,1,1,A4,17.622064,both,17.622064,17.622064
1,A4,2,1,A4,17.622064,both,17.622064,17.622064
2,A4,3,1,A4,17.622064,both,17.622064,17.622064
3,A4,4,1,A4,17.622064,both,17.622064,17.622064
4,A8,5,1,A8,21.102905,both,21.102905,21.102905
...,...,...,...,...,...,...,...,...
912,F3,922,1,F3,11.321542,both,11.321542,11.321542
913,F9,1036,1,F9,10.538572,both,10.538572,10.538572
914,F4,878,1,F4,9.617814,both,9.617814,9.617814
915,F4,953,1,F4,9.617814,both,9.617814,9.617814
916,F4,845,1,F4,9.617814,both,9.617814,9.617814

In [ ]:
df['total_expense'].describe()

count    917.000000
mean      34.806622
std       37.014441
min        4.724321
25%       17.622064
50%       19.174439
75%       35.764378
max      316.634246
Name: total_expense, dtype: float64

In [ ]:
offset = df[df['total_expense']>120]

In [ ]:
offset.head()

,id-product,id-client,quantities,reference,price,_merge,expense,total_expense
758,C7,819,1,C7,35.764378,both,35.764378,194.081501
759,C7,830,1,C7,35.764378,both,35.764378,197.385582
762,C7,943,1,C7,35.764378,both,35.764378,199.339644
771,D4,891,1,D4,79.158561,both,79.158561,237.475684
773,D4,831,1,D4,79.158561,both,79.158561,158.317123

In [ ]:
offset.shape

(35, 8)

In [ ]:
base1 = pd.DataFrame({'cliente':[1,8,7],
                      'gasto':[60,  120, 89]})
base2 = pd.DataFrame({'user':[8,7,1],
                      'exp':[6,  2, 15]})

In [ ]:
base1

   cliente  gasto
0        1     60
1        8    120
2        7     89

In [ ]:
base2

   user  exp
0     8    6
1     7    2
2     1   15

In [ ]:
base1.merge(base2, left_on='cliente', right_on='user')

   cliente  gasto  user  exp
0        1     60     1   15
1        8    120     8    6
2        7     89     7    2

In [ ]:
base1 = pd.DataFrame({'cliente':[1,8,7,8,6,1,1,8],
                      'gasto':[60,  120, 89,4,8,9,1,1]})

In [ ]:
base1['gasto total']=base1.groupby(by=['cliente'])['gasto'].transform("sum")

In [ ]:
base1

   cliente  gasto  gasto total
0        1     60           70
1        8    120          125
2        7     89           89
3        8      4          125
4        6      8            8
5        1      9           70
6        1      1           70
7        8      1          125

In [ ]:
base1[-base1.duplicated(subset=['cliente'], keep='first')].reset_index()

   index  cliente  gasto  gasto total
0      0        1     60           70
1      1        8    120          125
2      2        7     89           89
3      4        6      8            8